CREATE TABLE [dwh].[fact_rating]
(
	[rating_id] [int] IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[passenger_id] [int] NULL,
	[airport_id] [int] NULL,
	[airline_id] [int] NULL,
	[aircraft_id] [int] NULL,
	[lounge_id] [int] NULL,
	[airport_visit_date] [date] NULL,
	[lounge_visit_date] [date] NULL,
	[flight_date] [date] NULL,
	[airline_review_date] [date] NULL,
	[airport_review_date] [date] NULL,
	[lounge_review_date] [date] NULL,
	[seat_review_date] [date] NULL,
	[airline_overall_rating] [int] NULL,
	[airline_seat_comfort_rating] [int] NULL,
	[airline_cabin_staff_rating] [int] NULL,
	[airline_food_beverages_rating] [int] NULL,
	[airline_inflight_entertainment_rating] [int] NULL,
	[airline_ground_service_rating] [int] NULL,
	[airline_wifi_connectivity_rating] [int] NULL,
	[airline_value_money_rating] [int] NULL,
	[airline_recommended] [int] NULL,
	[airport_overall_rating] [int] NULL,
	[airport_queuing_rating] [int] NULL,
	[airport_terminal_cleanness_rating] [int] NULL,
	[airport_terminal_seating_rating] [int] NULL,
	[airport_terminal_signs_rating] [int] NULL,
	[airport_food_beverages_rating] [int] NULL,
	[airport_shopping_rating] [int] NULL,
	[airport_wifi_connectivity_rating] [int] NULL,
	[airport_staff_rating] [int] NULL,
	[airport_recommended] [int] NULL,
	[lounge_overall_rating] [int] NULL,
	[lounge_comfort_rating] [int] NULL,
	[lounge_cleanness_rating] [int] NULL,
	[lounge_bar_beverages_rating] [int] NULL,
	[lounge_catering_rating] [int] NULL,
	[lounge_washrooms_rating] [int] NULL,
	[lounge_wifi_connectivity_rating] [int] NULL,
	[lounge_staff_service_rating] [int] NULL,
	[lounge_recommended] [int] NULL,
	[seat_overall_rating] [int] NULL,
	[seat_legroom_rating] [int] NULL,
	[seat_recline_rating] [int] NULL,
	[seat_width_rating] [int] NULL,
	[seat_aisle_space_rating] [int] NULL,
	[seat_viewing_tv_rating] [int] NULL,
	[seat_power_supply_rating] [int] NULL,
	[seat_storage_rating] [int] NULL,
	[seat_recommended] [int] NULL,
	[overall_rating] [float] NULL,
	[overall_recommendation] [float] NULL,
	FOREIGN KEY ([passenger_id]) REFERENCES [dwh].[dim_passengers]([Id_author]),
	FOREIGN KEY ([airport_id]) REFERENCES [dwh].[dim_airports]([airport_id]),
	FOREIGN KEY ([airline_id]) REFERENCES [dwh].[dim_airlines]([airline_id]),
	FOREIGN KEY ([aircraft_id]) REFERENCES [dwh].[dim_aircrafts]([aircraft_id]),
	FOREIGN KEY ([lounge_id]) REFERENCES [dwh].[dim_lounges]([lounge_id]),
)
